// @generated by protoc-gen-es v1.8.0
// @generated from file rpc/proto/v1/auth.proto (package rpc.proto.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage, Struct } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message rpc.proto.v1.AuthenticateRequest
 */
export declare class AuthenticateRequest extends Message<AuthenticateRequest> {
  /**
   * @generated from field: string token = 1;
   */
  token: string;

  /**
   * @generated from field: google.protobuf.Struct optional_data = 10;
   */
  optionalData?: Struct;

  constructor(data?: PartialMessage<AuthenticateRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "rpc.proto.v1.AuthenticateRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AuthenticateRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AuthenticateRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AuthenticateRequest;

  static equals(a: AuthenticateRequest | PlainMessage<AuthenticateRequest> | undefined, b: AuthenticateRequest | PlainMessage<AuthenticateRequest> | undefined): boolean;
}

/**
 * @generated from message rpc.proto.v1.AuthenticateResponse
 */
export declare class AuthenticateResponse extends Message<AuthenticateResponse> {
  /**
   * @generated from field: string uuid = 1;
   */
  uuid: string;

  /**
   * @generated from field: string app_id = 2;
   */
  appId: string;

  /**
   * @generated from field: google.protobuf.Struct optional_data = 10;
   */
  optionalData?: Struct;

  constructor(data?: PartialMessage<AuthenticateResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "rpc.proto.v1.AuthenticateResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AuthenticateResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AuthenticateResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AuthenticateResponse;

  static equals(a: AuthenticateResponse | PlainMessage<AuthenticateResponse> | undefined, b: AuthenticateResponse | PlainMessage<AuthenticateResponse> | undefined): boolean;
}

