// @generated by protoc-gen-es v1.8.0
// @generated from file rpc/proto/v1/auth.proto (package rpc.proto.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3, Struct } from "@bufbuild/protobuf";

/**
 * @generated from message rpc.proto.v1.AuthenticateRequest
 */
export const AuthenticateRequest = /*@__PURE__*/ proto3.makeMessageType(
  "rpc.proto.v1.AuthenticateRequest",
  () => [
    { no: 1, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "optional_data", kind: "message", T: Struct },
  ],
);

/**
 * @generated from message rpc.proto.v1.AuthenticateResponse
 */
export const AuthenticateResponse = /*@__PURE__*/ proto3.makeMessageType(
  "rpc.proto.v1.AuthenticateResponse",
  () => [
    { no: 1, name: "uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "app_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "optional_data", kind: "message", T: Struct },
  ],
);

