// @generated by protoc-gen-es v1.8.0
// @generated from file rpc/proto/v1/backup.proto (package rpc.proto.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum rpc.proto.v1.BackupType
 */
export const BackupType = /*@__PURE__*/ proto3.makeEnum(
  "rpc.proto.v1.BackupType",
  [
    {no: 0, name: "BACKUP_TYPE_UNSPECIFIED", localName: "UNSPECIFIED"},
    {no: 1, name: "BACKUP_TYPE_CHALLENGE", localName: "CHALLENGE"},
    {no: 2, name: "BACKUP_TYPE_CREATE", localName: "CREATE"},
  ],
);

/**
 * @generated from message rpc.proto.v1.BackupRequest
 */
export const BackupRequest = /*@__PURE__*/ proto3.makeMessageType(
  "rpc.proto.v1.BackupRequest",
  () => [
    { no: 1, name: "type", kind: "enum", T: proto3.getEnumType(BackupType) },
    { no: 2, name: "params", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ],
);

/**
 * @generated from message rpc.proto.v1.BackupResponse
 */
export const BackupResponse = /*@__PURE__*/ proto3.makeMessageType(
  "rpc.proto.v1.BackupResponse",
  () => [
    { no: 1, name: "type", kind: "enum", T: proto3.getEnumType(BackupType) },
    { no: 2, name: "result", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ],
);

/**
 * @generated from message rpc.proto.v1.ChallengeInfo
 */
export const ChallengeInfo = /*@__PURE__*/ proto3.makeMessageType(
  "rpc.proto.v1.ChallengeInfo",
  () => [
    { no: 1, name: "uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "challenge_string", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "created_at", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "kind", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "target_object", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ],
);

/**
 * @generated from message rpc.proto.v1.CreateBackupParams
 */
export const CreateBackupParams = /*@__PURE__*/ proto3.makeMessageType(
  "rpc.proto.v1.CreateBackupParams",
  () => [
    { no: 1, name: "encrypted_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "sign_result", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

