// @generated by protoc-gen-es v1.8.0
// @generated from file rpc/proto/v1/backup.proto (package rpc.proto.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum rpc.proto.v1.BackupType
 */
export declare enum BackupType {
  /**
   * @generated from enum value: BACKUP_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: BACKUP_TYPE_CHALLENGE = 1;
   */
  CHALLENGE = 1,

  /**
   * @generated from enum value: BACKUP_TYPE_CREATE = 2;
   */
  CREATE = 2,
}

/**
 * @generated from message rpc.proto.v1.BackupRequest
 */
export declare class BackupRequest extends Message<BackupRequest> {
  /**
   * @generated from field: rpc.proto.v1.BackupType type = 1;
   */
  type: BackupType;

  /**
   * @generated from field: bytes params = 2;
   */
  params: Uint8Array;

  constructor(data?: PartialMessage<BackupRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "rpc.proto.v1.BackupRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BackupRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BackupRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BackupRequest;

  static equals(a: BackupRequest | PlainMessage<BackupRequest> | undefined, b: BackupRequest | PlainMessage<BackupRequest> | undefined): boolean;
}

/**
 * @generated from message rpc.proto.v1.BackupResponse
 */
export declare class BackupResponse extends Message<BackupResponse> {
  /**
   * @generated from field: rpc.proto.v1.BackupType type = 1;
   */
  type: BackupType;

  /**
   * @generated from field: bytes result = 2;
   */
  result: Uint8Array;

  constructor(data?: PartialMessage<BackupResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "rpc.proto.v1.BackupResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BackupResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BackupResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BackupResponse;

  static equals(a: BackupResponse | PlainMessage<BackupResponse> | undefined, b: BackupResponse | PlainMessage<BackupResponse> | undefined): boolean;
}

/**
 * @generated from message rpc.proto.v1.ChallengeInfo
 */
export declare class ChallengeInfo extends Message<ChallengeInfo> {
  /**
   * @generated from field: string uuid = 1;
   */
  uuid: string;

  /**
   * @generated from field: string challenge_string = 2;
   */
  challengeString: string;

  /**
   * @generated from field: int64 created_at = 3;
   */
  createdAt: bigint;

  /**
   * @generated from field: string kind = 4;
   */
  kind: string;

  /**
   * @generated from field: bytes target_object = 5;
   */
  targetObject: Uint8Array;

  constructor(data?: PartialMessage<ChallengeInfo>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "rpc.proto.v1.ChallengeInfo";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ChallengeInfo;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ChallengeInfo;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ChallengeInfo;

  static equals(a: ChallengeInfo | PlainMessage<ChallengeInfo> | undefined, b: ChallengeInfo | PlainMessage<ChallengeInfo> | undefined): boolean;
}

/**
 * @generated from message rpc.proto.v1.CreateBackupParams
 */
export declare class CreateBackupParams extends Message<CreateBackupParams> {
  /**
   * @generated from field: string encrypted_key = 1;
   */
  encryptedKey: string;

  /**
   * @generated from field: string sign_result = 2;
   */
  signResult: string;

  constructor(data?: PartialMessage<CreateBackupParams>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "rpc.proto.v1.CreateBackupParams";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateBackupParams;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateBackupParams;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateBackupParams;

  static equals(a: CreateBackupParams | PlainMessage<CreateBackupParams> | undefined, b: CreateBackupParams | PlainMessage<CreateBackupParams> | undefined): boolean;
}

