// @generated by protoc-gen-es v1.8.0
// @generated from file rpc/proto/v1/rpc.proto (package rpc.proto.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum rpc.proto.v1.Type
 */
export const Type = /*@__PURE__*/ proto3.makeEnum(
  "rpc.proto.v1.Type",
  [
    {no: 0, name: "TYPE_UNSPECIFIED", localName: "UNSPECIFIED"},
    {no: 1, name: "TYPE_DATA", localName: "DATA"},
    {no: 2, name: "TYPE_ERROR", localName: "ERROR"},
    {no: 3, name: "TYPE_DONE", localName: "DONE"},
  ],
);

/**
 * @generated from message rpc.proto.v1.Frame
 */
export const Frame = /*@__PURE__*/ proto3.makeMessageType(
  "rpc.proto.v1.Frame",
  () => [
    { no: 1, name: "type", kind: "enum", T: proto3.getEnumType(Type) },
    { no: 2, name: "id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "data", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ],
);

/**
 * @generated from message rpc.proto.v1.Error
 */
export const Error = /*@__PURE__*/ proto3.makeMessageType(
  "rpc.proto.v1.Error",
  () => [
    { no: 1, name: "code", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message rpc.proto.v1.Ok
 */
export const Ok = /*@__PURE__*/ proto3.makeMessageType(
  "rpc.proto.v1.Ok",
  () => [
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * Specific logic
 *
 * @generated from message rpc.proto.v1.Session
 */
export const Session = /*@__PURE__*/ proto3.makeMessageType(
  "rpc.proto.v1.Session",
  () => [
    { no: 1, name: "session_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

