// @generated by protoc-gen-es v1.8.0
// @generated from file rpc/proto/v1/sign.proto (package rpc.proto.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum rpc.proto.v1.SignType
 */
export const SignType = /*@__PURE__*/ proto3.makeEnum(
  "rpc.proto.v1.SignType",
  [
    {no: 0, name: "SIGN_TYPE_UNSPECIFIED", localName: "UNSPECIFIED"},
    {no: 1, name: "SIGN_TYPE_MESSAGE", localName: "MESSAGE"},
    {no: 2, name: "SIGN_TYPE_TRANSACTION", localName: "TRANSACTION"},
  ],
);

/**
 * @generated from message rpc.proto.v1.SignRequest
 */
export const SignRequest = /*@__PURE__*/ proto3.makeMessageType(
  "rpc.proto.v1.SignRequest",
  () => [
    { no: 1, name: "type", kind: "enum", T: proto3.getEnumType(SignType) },
    { no: 2, name: "params", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ],
);

/**
 * @generated from message rpc.proto.v1.SignResponse
 */
export const SignResponse = /*@__PURE__*/ proto3.makeMessageType(
  "rpc.proto.v1.SignResponse",
  () => [
    { no: 1, name: "result", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ],
);

/**
 * @generated from message rpc.proto.v1.SendTransactionResponse
 */
export const SendTransactionResponse = /*@__PURE__*/ proto3.makeMessageType(
  "rpc.proto.v1.SendTransactionResponse",
  () => [
    { no: 1, name: "tx_hash", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

