// @generated by protoc-gen-es v1.8.0
// @generated from file rpc/proto/v1/sign.proto (package rpc.proto.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum rpc.proto.v1.SignType
 */
export declare enum SignType {
  /**
   * @generated from enum value: SIGN_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SIGN_TYPE_MESSAGE = 1;
   */
  MESSAGE = 1,

  /**
   * @generated from enum value: SIGN_TYPE_TRANSACTION = 2;
   */
  TRANSACTION = 2,
}

/**
 * @generated from message rpc.proto.v1.SignRequest
 */
export declare class SignRequest extends Message<SignRequest> {
  /**
   * @generated from field: rpc.proto.v1.SignType type = 1;
   */
  type: SignType;

  /**
   * @generated from field: bytes params = 2;
   */
  params: Uint8Array;

  constructor(data?: PartialMessage<SignRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "rpc.proto.v1.SignRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SignRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SignRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SignRequest;

  static equals(a: SignRequest | PlainMessage<SignRequest> | undefined, b: SignRequest | PlainMessage<SignRequest> | undefined): boolean;
}

/**
 * @generated from message rpc.proto.v1.SignResponse
 */
export declare class SignResponse extends Message<SignResponse> {
  /**
   * @generated from field: bytes result = 1;
   */
  result: Uint8Array;

  constructor(data?: PartialMessage<SignResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "rpc.proto.v1.SignResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SignResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SignResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SignResponse;

  static equals(a: SignResponse | PlainMessage<SignResponse> | undefined, b: SignResponse | PlainMessage<SignResponse> | undefined): boolean;
}

/**
 * @generated from message rpc.proto.v1.SendTransactionResponse
 */
export declare class SendTransactionResponse extends Message<SendTransactionResponse> {
  /**
   * @generated from field: string tx_hash = 1;
   */
  txHash: string;

  constructor(data?: PartialMessage<SendTransactionResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "rpc.proto.v1.SendTransactionResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SendTransactionResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SendTransactionResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SendTransactionResponse;

  static equals(a: SendTransactionResponse | PlainMessage<SendTransactionResponse> | undefined, b: SendTransactionResponse | PlainMessage<SendTransactionResponse> | undefined): boolean;
}

