// @generated by protoc-gen-es v1.8.0
// @generated from file sdk/proto/v1/sdk.proto (package sdk.proto.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message sdk.proto.v1.Error
 */
export declare class Error extends Message<Error> {
  /**
   * @generated from field: uint32 code = 1;
   */
  code: number;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  constructor(data?: PartialMessage<Error>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "sdk.proto.v1.Error";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Error;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Error;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Error;

  static equals(a: Error | PlainMessage<Error> | undefined, b: Error | PlainMessage<Error> | undefined): boolean;
}

/**
 * @generated from message sdk.proto.v1.KeygenRequest
 */
export declare class KeygenRequest extends Message<KeygenRequest> {
  /**
   * @generated from field: string websocket_url = 1;
   */
  websocketUrl: string;

  /**
   * @generated from field: string access_token = 2;
   */
  accessToken: string;

  /**
   * @generated from field: double timeout = 3;
   */
  timeout: number;

  /**
   * @generated from field: sdk.proto.v1.TrackParams track_params = 4;
   */
  trackParams?: TrackParams;

  /**
   * @generated from field: string optional_params = 10;
   */
  optionalParams: string;

  constructor(data?: PartialMessage<KeygenRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "sdk.proto.v1.KeygenRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): KeygenRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): KeygenRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): KeygenRequest;

  static equals(a: KeygenRequest | PlainMessage<KeygenRequest> | undefined, b: KeygenRequest | PlainMessage<KeygenRequest> | undefined): boolean;
}

/**
 * @generated from message sdk.proto.v1.KeygenResponse
 */
export declare class KeygenResponse extends Message<KeygenResponse> {
  /**
   * @generated from field: string key = 1;
   */
  key: string;

  /**
   * @generated from field: sdk.proto.v1.Meta meta = 2;
   */
  meta?: Meta;

  /**
   * @generated from field: sdk.proto.v1.Error error = 10;
   */
  error?: Error;

  constructor(data?: PartialMessage<KeygenResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "sdk.proto.v1.KeygenResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): KeygenResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): KeygenResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): KeygenResponse;

  static equals(a: KeygenResponse | PlainMessage<KeygenResponse> | undefined, b: KeygenResponse | PlainMessage<KeygenResponse> | undefined): boolean;
}

/**
 * @generated from message sdk.proto.v1.SignMessageRequest
 */
export declare class SignMessageRequest extends Message<SignMessageRequest> {
  /**
   * @generated from field: string websocket_url = 1;
   */
  websocketUrl: string;

  /**
   * @generated from field: string access_token = 2;
   */
  accessToken: string;

  /**
   * @generated from field: string key = 3;
   */
  key: string;

  /**
   * @generated from field: string sign_message = 4;
   */
  signMessage: string;

  /**
   * @generated from field: double timeout = 5;
   */
  timeout: number;

  /**
   * @generated from field: sdk.proto.v1.TrackParams track_params = 6;
   */
  trackParams?: TrackParams;

  /**
   * @generated from field: string optional_params = 10;
   */
  optionalParams: string;

  constructor(data?: PartialMessage<SignMessageRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "sdk.proto.v1.SignMessageRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SignMessageRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SignMessageRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SignMessageRequest;

  static equals(a: SignMessageRequest | PlainMessage<SignMessageRequest> | undefined, b: SignMessageRequest | PlainMessage<SignMessageRequest> | undefined): boolean;
}

/**
 * @generated from message sdk.proto.v1.SignMessageResponse
 */
export declare class SignMessageResponse extends Message<SignMessageResponse> {
  /**
   * @generated from field: string signature = 1;
   */
  signature: string;

  /**
   * @generated from field: sdk.proto.v1.Meta meta = 2;
   */
  meta?: Meta;

  /**
   * @generated from field: sdk.proto.v1.Error error = 10;
   */
  error?: Error;

  constructor(data?: PartialMessage<SignMessageResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "sdk.proto.v1.SignMessageResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SignMessageResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SignMessageResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SignMessageResponse;

  static equals(a: SignMessageResponse | PlainMessage<SignMessageResponse> | undefined, b: SignMessageResponse | PlainMessage<SignMessageResponse> | undefined): boolean;
}

/**
 * @generated from message sdk.proto.v1.SendTransactionRequest
 */
export declare class SendTransactionRequest extends Message<SendTransactionRequest> {
  /**
   * @generated from field: string websocket_url = 1;
   */
  websocketUrl: string;

  /**
   * @generated from field: string access_token = 2;
   */
  accessToken: string;

  /**
   * @generated from field: string key = 3;
   */
  key: string;

  /**
   * @generated from field: string tx_json_data = 4;
   */
  txJsonData: string;

  /**
   * @generated from field: string chain_rpc_url = 5;
   */
  chainRpcUrl: string;

  /**
   * @generated from field: double timeout = 6;
   */
  timeout: number;

  /**
   * @generated from field: sdk.proto.v1.TrackParams track_params = 7;
   */
  trackParams?: TrackParams;

  /**
   * @generated from field: string optional_params = 10;
   */
  optionalParams: string;

  constructor(data?: PartialMessage<SendTransactionRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "sdk.proto.v1.SendTransactionRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SendTransactionRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SendTransactionRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SendTransactionRequest;

  static equals(a: SendTransactionRequest | PlainMessage<SendTransactionRequest> | undefined, b: SendTransactionRequest | PlainMessage<SendTransactionRequest> | undefined): boolean;
}

/**
 * @generated from message sdk.proto.v1.SendTransactionResponse
 */
export declare class SendTransactionResponse extends Message<SendTransactionResponse> {
  /**
   * @generated from field: string tx_hash = 1;
   */
  txHash: string;

  /**
   * @generated from field: sdk.proto.v1.Meta meta = 2;
   */
  meta?: Meta;

  /**
   * @generated from field: sdk.proto.v1.Error error = 10;
   */
  error?: Error;

  constructor(data?: PartialMessage<SendTransactionResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "sdk.proto.v1.SendTransactionResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SendTransactionResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SendTransactionResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SendTransactionResponse;

  static equals(a: SendTransactionResponse | PlainMessage<SendTransactionResponse> | undefined, b: SendTransactionResponse | PlainMessage<SendTransactionResponse> | undefined): boolean;
}

/**
 * @generated from message sdk.proto.v1.GetAddressFromKeyRequest
 */
export declare class GetAddressFromKeyRequest extends Message<GetAddressFromKeyRequest> {
  /**
   * @generated from field: string key = 1;
   */
  key: string;

  /**
   * @generated from field: string optional_params = 10;
   */
  optionalParams: string;

  constructor(data?: PartialMessage<GetAddressFromKeyRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "sdk.proto.v1.GetAddressFromKeyRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAddressFromKeyRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAddressFromKeyRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAddressFromKeyRequest;

  static equals(a: GetAddressFromKeyRequest | PlainMessage<GetAddressFromKeyRequest> | undefined, b: GetAddressFromKeyRequest | PlainMessage<GetAddressFromKeyRequest> | undefined): boolean;
}

/**
 * @generated from message sdk.proto.v1.GetAddressFromKeyResponse
 */
export declare class GetAddressFromKeyResponse extends Message<GetAddressFromKeyResponse> {
  /**
   * @generated from field: string data = 1;
   */
  data: string;

  /**
   * @generated from field: sdk.proto.v1.Error error = 10;
   */
  error?: Error;

  constructor(data?: PartialMessage<GetAddressFromKeyResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "sdk.proto.v1.GetAddressFromKeyResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAddressFromKeyResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAddressFromKeyResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAddressFromKeyResponse;

  static equals(a: GetAddressFromKeyResponse | PlainMessage<GetAddressFromKeyResponse> | undefined, b: GetAddressFromKeyResponse | PlainMessage<GetAddressFromKeyResponse> | undefined): boolean;
}

/**
 * @generated from message sdk.proto.v1.EncryptDataRequest
 */
export declare class EncryptDataRequest extends Message<EncryptDataRequest> {
  /**
   * @generated from field: string access_token = 1;
   */
  accessToken: string;

  /**
   * @generated from field: string key = 2;
   */
  key: string;

  /**
   * @generated from field: string password = 3;
   */
  password: string;

  /**
   * @generated from field: string optional_params = 10;
   */
  optionalParams: string;

  constructor(data?: PartialMessage<EncryptDataRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "sdk.proto.v1.EncryptDataRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EncryptDataRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EncryptDataRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EncryptDataRequest;

  static equals(a: EncryptDataRequest | PlainMessage<EncryptDataRequest> | undefined, b: EncryptDataRequest | PlainMessage<EncryptDataRequest> | undefined): boolean;
}

/**
 * @generated from message sdk.proto.v1.EncryptDataResponse
 */
export declare class EncryptDataResponse extends Message<EncryptDataResponse> {
  /**
   * @generated from field: string data = 1;
   */
  data: string;

  /**
   * @generated from field: sdk.proto.v1.Error error = 10;
   */
  error?: Error;

  constructor(data?: PartialMessage<EncryptDataResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "sdk.proto.v1.EncryptDataResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EncryptDataResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EncryptDataResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EncryptDataResponse;

  static equals(a: EncryptDataResponse | PlainMessage<EncryptDataResponse> | undefined, b: EncryptDataResponse | PlainMessage<EncryptDataResponse> | undefined): boolean;
}

/**
 * @generated from message sdk.proto.v1.EncryptDataV2Request
 */
export declare class EncryptDataV2Request extends Message<EncryptDataV2Request> {
  /**
   * @generated from field: string access_token = 1;
   */
  accessToken: string;

  /**
   * @generated from field: string key = 2;
   */
  key: string;

  /**
   * @generated from field: string password = 3;
   */
  password: string;

  /**
   * @generated from field: uint32 recovery_phrase_length = 4;
   */
  recoveryPhraseLength: number;

  /**
   * @generated from field: string optional_params = 10;
   */
  optionalParams: string;

  constructor(data?: PartialMessage<EncryptDataV2Request>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "sdk.proto.v1.EncryptDataV2Request";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EncryptDataV2Request;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EncryptDataV2Request;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EncryptDataV2Request;

  static equals(a: EncryptDataV2Request | PlainMessage<EncryptDataV2Request> | undefined, b: EncryptDataV2Request | PlainMessage<EncryptDataV2Request> | undefined): boolean;
}

/**
 * @generated from message sdk.proto.v1.EncryptDataV2Response
 */
export declare class EncryptDataV2Response extends Message<EncryptDataV2Response> {
  /**
   * @generated from field: string encrypted_key = 1;
   */
  encryptedKey: string;

  /**
   * @generated from field: string recovery_phrase = 2;
   */
  recoveryPhrase: string;

  /**
   * @generated from field: sdk.proto.v1.Error error = 10;
   */
  error?: Error;

  constructor(data?: PartialMessage<EncryptDataV2Response>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "sdk.proto.v1.EncryptDataV2Response";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EncryptDataV2Response;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EncryptDataV2Response;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EncryptDataV2Response;

  static equals(a: EncryptDataV2Response | PlainMessage<EncryptDataV2Response> | undefined, b: EncryptDataV2Response | PlainMessage<EncryptDataV2Response> | undefined): boolean;
}

/**
 * @generated from message sdk.proto.v1.DecryptDataRequest
 */
export declare class DecryptDataRequest extends Message<DecryptDataRequest> {
  /**
   * @generated from field: string access_token = 1;
   */
  accessToken: string;

  /**
   * @generated from field: string encrypted_key = 2;
   */
  encryptedKey: string;

  /**
   * @generated from field: string password = 3;
   */
  password: string;

  /**
   * @generated from field: string optional_params = 10;
   */
  optionalParams: string;

  constructor(data?: PartialMessage<DecryptDataRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "sdk.proto.v1.DecryptDataRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DecryptDataRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DecryptDataRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DecryptDataRequest;

  static equals(a: DecryptDataRequest | PlainMessage<DecryptDataRequest> | undefined, b: DecryptDataRequest | PlainMessage<DecryptDataRequest> | undefined): boolean;
}

/**
 * @generated from message sdk.proto.v1.DecryptDataResponse
 */
export declare class DecryptDataResponse extends Message<DecryptDataResponse> {
  /**
   * @generated from field: string data = 1;
   */
  data: string;

  /**
   * @generated from field: sdk.proto.v1.Error error = 10;
   */
  error?: Error;

  constructor(data?: PartialMessage<DecryptDataResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "sdk.proto.v1.DecryptDataResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DecryptDataResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DecryptDataResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DecryptDataResponse;

  static equals(a: DecryptDataResponse | PlainMessage<DecryptDataResponse> | undefined, b: DecryptDataResponse | PlainMessage<DecryptDataResponse> | undefined): boolean;
}

/**
 * @generated from message sdk.proto.v1.DecryptDataV2Request
 */
export declare class DecryptDataV2Request extends Message<DecryptDataV2Request> {
  /**
   * @generated from field: string access_token = 1;
   */
  accessToken: string;

  /**
   * @generated from field: string encrypted_key = 2;
   */
  encryptedKey: string;

  /**
   * @generated from field: string password = 3;
   */
  password: string;

  /**
   * @generated from field: string recovery_phrase = 4;
   */
  recoveryPhrase: string;

  /**
   * @generated from field: string optional_params = 10;
   */
  optionalParams: string;

  constructor(data?: PartialMessage<DecryptDataV2Request>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "sdk.proto.v1.DecryptDataV2Request";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DecryptDataV2Request;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DecryptDataV2Request;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DecryptDataV2Request;

  static equals(a: DecryptDataV2Request | PlainMessage<DecryptDataV2Request> | undefined, b: DecryptDataV2Request | PlainMessage<DecryptDataV2Request> | undefined): boolean;
}

/**
 * @generated from message sdk.proto.v1.DecryptDataV2Response
 */
export declare class DecryptDataV2Response extends Message<DecryptDataV2Response> {
  /**
   * @generated from field: string key = 1;
   */
  key: string;

  /**
   * @generated from field: sdk.proto.v1.Error error = 10;
   */
  error?: Error;

  constructor(data?: PartialMessage<DecryptDataV2Response>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "sdk.proto.v1.DecryptDataV2Response";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DecryptDataV2Response;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DecryptDataV2Response;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DecryptDataV2Response;

  static equals(a: DecryptDataV2Response | PlainMessage<DecryptDataV2Response> | undefined, b: DecryptDataV2Response | PlainMessage<DecryptDataV2Response> | undefined): boolean;
}

/**
 * @generated from message sdk.proto.v1.CreateBackupKeyRequest
 */
export declare class CreateBackupKeyRequest extends Message<CreateBackupKeyRequest> {
  /**
   * @generated from field: string websocket_url = 1;
   */
  websocketUrl: string;

  /**
   * @generated from field: string access_token = 2;
   */
  accessToken: string;

  /**
   * @generated from field: string encrypted_key = 3;
   */
  encryptedKey: string;

  /**
   * @generated from field: string key = 4;
   */
  key: string;

  /**
   * @generated from field: double timeout = 5;
   */
  timeout: number;

  /**
   * @generated from field: sdk.proto.v1.TrackParams track_params = 6;
   */
  trackParams?: TrackParams;

  /**
   * @generated from field: string optional_params = 10;
   */
  optionalParams: string;

  constructor(data?: PartialMessage<CreateBackupKeyRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "sdk.proto.v1.CreateBackupKeyRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateBackupKeyRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateBackupKeyRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateBackupKeyRequest;

  static equals(a: CreateBackupKeyRequest | PlainMessage<CreateBackupKeyRequest> | undefined, b: CreateBackupKeyRequest | PlainMessage<CreateBackupKeyRequest> | undefined): boolean;
}

/**
 * @generated from message sdk.proto.v1.CreateBackupKeyResponse
 */
export declare class CreateBackupKeyResponse extends Message<CreateBackupKeyResponse> {
  /**
   * @generated from field: string encrypted_key = 1;
   */
  encryptedKey: string;

  /**
   * @generated from field: sdk.proto.v1.Meta meta = 2;
   */
  meta?: Meta;

  /**
   * @generated from field: sdk.proto.v1.Error error = 10;
   */
  error?: Error;

  constructor(data?: PartialMessage<CreateBackupKeyResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "sdk.proto.v1.CreateBackupKeyResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateBackupKeyResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateBackupKeyResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateBackupKeyResponse;

  static equals(a: CreateBackupKeyResponse | PlainMessage<CreateBackupKeyResponse> | undefined, b: CreateBackupKeyResponse | PlainMessage<CreateBackupKeyResponse> | undefined): boolean;
}

/**
 * @generated from message sdk.proto.v1.GetBackupKeyRequest
 */
export declare class GetBackupKeyRequest extends Message<GetBackupKeyRequest> {
  /**
   * @generated from field: string http_url = 1;
   */
  httpUrl: string;

  /**
   * @generated from field: string access_token = 2;
   */
  accessToken: string;

  /**
   * @generated from field: double timeout = 3;
   */
  timeout: number;

  /**
   * @generated from field: sdk.proto.v1.TrackParams track_params = 4;
   */
  trackParams?: TrackParams;

  /**
   * @generated from field: string optional_params = 10;
   */
  optionalParams: string;

  constructor(data?: PartialMessage<GetBackupKeyRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "sdk.proto.v1.GetBackupKeyRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetBackupKeyRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetBackupKeyRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetBackupKeyRequest;

  static equals(a: GetBackupKeyRequest | PlainMessage<GetBackupKeyRequest> | undefined, b: GetBackupKeyRequest | PlainMessage<GetBackupKeyRequest> | undefined): boolean;
}

/**
 * @generated from message sdk.proto.v1.GetBackupKeyResponse
 */
export declare class GetBackupKeyResponse extends Message<GetBackupKeyResponse> {
  /**
   * @generated from field: string encrypted_key = 1;
   */
  encryptedKey: string;

  /**
   * @generated from field: int64 updated_at = 2;
   */
  updatedAt: bigint;

  /**
   * @generated from field: sdk.proto.v1.Meta meta = 3;
   */
  meta?: Meta;

  /**
   * @generated from field: sdk.proto.v1.Error error = 10;
   */
  error?: Error;

  constructor(data?: PartialMessage<GetBackupKeyResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "sdk.proto.v1.GetBackupKeyResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetBackupKeyResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetBackupKeyResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetBackupKeyResponse;

  static equals(a: GetBackupKeyResponse | PlainMessage<GetBackupKeyResponse> | undefined, b: GetBackupKeyResponse | PlainMessage<GetBackupKeyResponse> | undefined): boolean;
}

/**
 * @generated from message sdk.proto.v1.GetCurrentUserProfileRequest
 */
export declare class GetCurrentUserProfileRequest extends Message<GetCurrentUserProfileRequest> {
  /**
   * @generated from field: string http_url = 1;
   */
  httpUrl: string;

  /**
   * @generated from field: string access_token = 2;
   */
  accessToken: string;

  /**
   * @generated from field: double timeout = 3;
   */
  timeout: number;

  /**
   * @generated from field: sdk.proto.v1.TrackParams track_params = 4;
   */
  trackParams?: TrackParams;

  /**
   * @generated from field: string optional_params = 10;
   */
  optionalParams: string;

  constructor(data?: PartialMessage<GetCurrentUserProfileRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "sdk.proto.v1.GetCurrentUserProfileRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetCurrentUserProfileRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetCurrentUserProfileRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetCurrentUserProfileRequest;

  static equals(a: GetCurrentUserProfileRequest | PlainMessage<GetCurrentUserProfileRequest> | undefined, b: GetCurrentUserProfileRequest | PlainMessage<GetCurrentUserProfileRequest> | undefined): boolean;
}

/**
 * @generated from message sdk.proto.v1.GetCurrentUserProfileResponse
 */
export declare class GetCurrentUserProfileResponse extends Message<GetCurrentUserProfileResponse> {
  /**
   * @generated from field: string address = 1;
   */
  address: string;

  /**
   * @generated from field: int64 updated_at = 2;
   */
  updatedAt: bigint;

  /**
   * @generated from field: sdk.proto.v1.Meta meta = 3;
   */
  meta?: Meta;

  /**
   * @generated from field: sdk.proto.v1.Error error = 10;
   */
  error?: Error;

  constructor(data?: PartialMessage<GetCurrentUserProfileResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "sdk.proto.v1.GetCurrentUserProfileResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetCurrentUserProfileResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetCurrentUserProfileResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetCurrentUserProfileResponse;

  static equals(a: GetCurrentUserProfileResponse | PlainMessage<GetCurrentUserProfileResponse> | undefined, b: GetCurrentUserProfileResponse | PlainMessage<GetCurrentUserProfileResponse> | undefined): boolean;
}

/**
 * @generated from message sdk.proto.v1.KeyDistributionRequest
 */
export declare class KeyDistributionRequest extends Message<KeyDistributionRequest> {
  /**
   * @generated from field: string websocket_url = 1;
   */
  websocketUrl: string;

  /**
   * @generated from field: string access_token = 2;
   */
  accessToken: string;

  /**
   * @generated from field: string private_key = 3;
   */
  privateKey: string;

  /**
   * @generated from field: double timeout = 4;
   */
  timeout: number;

  /**
   * @generated from field: sdk.proto.v1.TrackParams track_params = 5;
   */
  trackParams?: TrackParams;

  /**
   * @generated from field: string optional_params = 10;
   */
  optionalParams: string;

  constructor(data?: PartialMessage<KeyDistributionRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "sdk.proto.v1.KeyDistributionRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): KeyDistributionRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): KeyDistributionRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): KeyDistributionRequest;

  static equals(a: KeyDistributionRequest | PlainMessage<KeyDistributionRequest> | undefined, b: KeyDistributionRequest | PlainMessage<KeyDistributionRequest> | undefined): boolean;
}

/**
 * @generated from message sdk.proto.v1.KeyDistributionResponse
 */
export declare class KeyDistributionResponse extends Message<KeyDistributionResponse> {
  /**
   * @generated from field: string key = 1;
   */
  key: string;

  /**
   * @generated from field: sdk.proto.v1.Meta meta = 2;
   */
  meta?: Meta;

  /**
   * @generated from field: sdk.proto.v1.Error error = 10;
   */
  error?: Error;

  constructor(data?: PartialMessage<KeyDistributionResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "sdk.proto.v1.KeyDistributionResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): KeyDistributionResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): KeyDistributionResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): KeyDistributionResponse;

  static equals(a: KeyDistributionResponse | PlainMessage<KeyDistributionResponse> | undefined, b: KeyDistributionResponse | PlainMessage<KeyDistributionResponse> | undefined): boolean;
}

/**
 * @generated from message sdk.proto.v1.RefreshKeyRequest
 */
export declare class RefreshKeyRequest extends Message<RefreshKeyRequest> {
  /**
   * @generated from field: string websocket_url = 1;
   */
  websocketUrl: string;

  /**
   * @generated from field: string access_token = 2;
   */
  accessToken: string;

  /**
   * @generated from field: string key = 3;
   */
  key: string;

  /**
   * @generated from field: double timeout = 4;
   */
  timeout: number;

  /**
   * @generated from field: sdk.proto.v1.TrackParams track_params = 5;
   */
  trackParams?: TrackParams;

  /**
   * @generated from field: string optional_params = 10;
   */
  optionalParams: string;

  constructor(data?: PartialMessage<RefreshKeyRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "sdk.proto.v1.RefreshKeyRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RefreshKeyRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RefreshKeyRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RefreshKeyRequest;

  static equals(a: RefreshKeyRequest | PlainMessage<RefreshKeyRequest> | undefined, b: RefreshKeyRequest | PlainMessage<RefreshKeyRequest> | undefined): boolean;
}

/**
 * @generated from message sdk.proto.v1.RefreshKeyResponse
 */
export declare class RefreshKeyResponse extends Message<RefreshKeyResponse> {
  /**
   * @generated from field: string key = 1;
   */
  key: string;

  /**
   * @generated from field: sdk.proto.v1.Meta meta = 2;
   */
  meta?: Meta;

  /**
   * @generated from field: sdk.proto.v1.Error error = 10;
   */
  error?: Error;

  constructor(data?: PartialMessage<RefreshKeyResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "sdk.proto.v1.RefreshKeyResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RefreshKeyResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RefreshKeyResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RefreshKeyResponse;

  static equals(a: RefreshKeyResponse | PlainMessage<RefreshKeyResponse> | undefined, b: RefreshKeyResponse | PlainMessage<RefreshKeyResponse> | undefined): boolean;
}

/**
 * @generated from message sdk.proto.v1.Meta
 */
export declare class Meta extends Message<Meta> {
  /**
   * @generated from field: string request_id = 1;
   */
  requestId: string;

  /**
   * @generated from field: string uuid = 2;
   */
  uuid: string;

  constructor(data?: PartialMessage<Meta>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "sdk.proto.v1.Meta";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Meta;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Meta;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Meta;

  static equals(a: Meta | PlainMessage<Meta> | undefined, b: Meta | PlainMessage<Meta> | undefined): boolean;
}

/**
 * @generated from message sdk.proto.v1.TrackParams
 */
export declare class TrackParams extends Message<TrackParams> {
  /**
   * @generated from field: bool enable = 1;
   */
  enable: boolean;

  /**
   * @generated from field: double timeout = 2;
   */
  timeout: number;

  constructor(data?: PartialMessage<TrackParams>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "sdk.proto.v1.TrackParams";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TrackParams;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TrackParams;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TrackParams;

  static equals(a: TrackParams | PlainMessage<TrackParams> | undefined, b: TrackParams | PlainMessage<TrackParams> | undefined): boolean;
}

