// @generated by protoc-gen-es v1.8.0
// @generated from file sdk/proto/v1/sdk.proto (package sdk.proto.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message sdk.proto.v1.Error
 */
export const Error = /*@__PURE__*/ proto3.makeMessageType(
  "sdk.proto.v1.Error",
  () => [
    { no: 1, name: "code", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message sdk.proto.v1.KeygenRequest
 */
export const KeygenRequest = /*@__PURE__*/ proto3.makeMessageType(
  "sdk.proto.v1.KeygenRequest",
  () => [
    { no: 1, name: "websocket_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "access_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "timeout", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 4, name: "track_params", kind: "message", T: TrackParams },
    { no: 10, name: "optional_params", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message sdk.proto.v1.KeygenResponse
 */
export const KeygenResponse = /*@__PURE__*/ proto3.makeMessageType(
  "sdk.proto.v1.KeygenResponse",
  () => [
    { no: 1, name: "key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "meta", kind: "message", T: Meta },
    { no: 10, name: "error", kind: "message", T: Error },
  ],
);

/**
 * @generated from message sdk.proto.v1.SignMessageRequest
 */
export const SignMessageRequest = /*@__PURE__*/ proto3.makeMessageType(
  "sdk.proto.v1.SignMessageRequest",
  () => [
    { no: 1, name: "websocket_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "access_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "sign_message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "timeout", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 6, name: "track_params", kind: "message", T: TrackParams },
    { no: 10, name: "optional_params", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message sdk.proto.v1.SignMessageResponse
 */
export const SignMessageResponse = /*@__PURE__*/ proto3.makeMessageType(
  "sdk.proto.v1.SignMessageResponse",
  () => [
    { no: 1, name: "signature", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "meta", kind: "message", T: Meta },
    { no: 10, name: "error", kind: "message", T: Error },
  ],
);

/**
 * @generated from message sdk.proto.v1.SendTransactionRequest
 */
export const SendTransactionRequest = /*@__PURE__*/ proto3.makeMessageType(
  "sdk.proto.v1.SendTransactionRequest",
  () => [
    { no: 1, name: "websocket_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "access_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "tx_json_data", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "chain_rpc_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "timeout", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 7, name: "track_params", kind: "message", T: TrackParams },
    { no: 10, name: "optional_params", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message sdk.proto.v1.SendTransactionResponse
 */
export const SendTransactionResponse = /*@__PURE__*/ proto3.makeMessageType(
  "sdk.proto.v1.SendTransactionResponse",
  () => [
    { no: 1, name: "tx_hash", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "meta", kind: "message", T: Meta },
    { no: 10, name: "error", kind: "message", T: Error },
  ],
);

/**
 * @generated from message sdk.proto.v1.GetAddressFromKeyRequest
 */
export const GetAddressFromKeyRequest = /*@__PURE__*/ proto3.makeMessageType(
  "sdk.proto.v1.GetAddressFromKeyRequest",
  () => [
    { no: 1, name: "key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "optional_params", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message sdk.proto.v1.GetAddressFromKeyResponse
 */
export const GetAddressFromKeyResponse = /*@__PURE__*/ proto3.makeMessageType(
  "sdk.proto.v1.GetAddressFromKeyResponse",
  () => [
    { no: 1, name: "data", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "error", kind: "message", T: Error },
  ],
);

/**
 * @generated from message sdk.proto.v1.EncryptDataRequest
 */
export const EncryptDataRequest = /*@__PURE__*/ proto3.makeMessageType(
  "sdk.proto.v1.EncryptDataRequest",
  () => [
    { no: 1, name: "access_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "password", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "optional_params", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message sdk.proto.v1.EncryptDataResponse
 */
export const EncryptDataResponse = /*@__PURE__*/ proto3.makeMessageType(
  "sdk.proto.v1.EncryptDataResponse",
  () => [
    { no: 1, name: "data", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "error", kind: "message", T: Error },
  ],
);

/**
 * @generated from message sdk.proto.v1.EncryptDataV2Request
 */
export const EncryptDataV2Request = /*@__PURE__*/ proto3.makeMessageType(
  "sdk.proto.v1.EncryptDataV2Request",
  () => [
    { no: 1, name: "access_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "password", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "recovery_phrase_length", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 10, name: "optional_params", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message sdk.proto.v1.EncryptDataV2Response
 */
export const EncryptDataV2Response = /*@__PURE__*/ proto3.makeMessageType(
  "sdk.proto.v1.EncryptDataV2Response",
  () => [
    { no: 1, name: "encrypted_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "recovery_phrase", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "error", kind: "message", T: Error },
  ],
);

/**
 * @generated from message sdk.proto.v1.DecryptDataRequest
 */
export const DecryptDataRequest = /*@__PURE__*/ proto3.makeMessageType(
  "sdk.proto.v1.DecryptDataRequest",
  () => [
    { no: 1, name: "access_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "encrypted_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "password", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "optional_params", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message sdk.proto.v1.DecryptDataResponse
 */
export const DecryptDataResponse = /*@__PURE__*/ proto3.makeMessageType(
  "sdk.proto.v1.DecryptDataResponse",
  () => [
    { no: 1, name: "data", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "error", kind: "message", T: Error },
  ],
);

/**
 * @generated from message sdk.proto.v1.DecryptDataV2Request
 */
export const DecryptDataV2Request = /*@__PURE__*/ proto3.makeMessageType(
  "sdk.proto.v1.DecryptDataV2Request",
  () => [
    { no: 1, name: "access_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "encrypted_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "password", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "recovery_phrase", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "optional_params", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message sdk.proto.v1.DecryptDataV2Response
 */
export const DecryptDataV2Response = /*@__PURE__*/ proto3.makeMessageType(
  "sdk.proto.v1.DecryptDataV2Response",
  () => [
    { no: 1, name: "key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "error", kind: "message", T: Error },
  ],
);

/**
 * @generated from message sdk.proto.v1.CreateBackupKeyRequest
 */
export const CreateBackupKeyRequest = /*@__PURE__*/ proto3.makeMessageType(
  "sdk.proto.v1.CreateBackupKeyRequest",
  () => [
    { no: 1, name: "websocket_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "access_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "encrypted_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "timeout", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 6, name: "track_params", kind: "message", T: TrackParams },
    { no: 10, name: "optional_params", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message sdk.proto.v1.CreateBackupKeyResponse
 */
export const CreateBackupKeyResponse = /*@__PURE__*/ proto3.makeMessageType(
  "sdk.proto.v1.CreateBackupKeyResponse",
  () => [
    { no: 1, name: "encrypted_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "meta", kind: "message", T: Meta },
    { no: 10, name: "error", kind: "message", T: Error },
  ],
);

/**
 * @generated from message sdk.proto.v1.GetBackupKeyRequest
 */
export const GetBackupKeyRequest = /*@__PURE__*/ proto3.makeMessageType(
  "sdk.proto.v1.GetBackupKeyRequest",
  () => [
    { no: 1, name: "http_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "access_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "timeout", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 4, name: "track_params", kind: "message", T: TrackParams },
    { no: 10, name: "optional_params", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message sdk.proto.v1.GetBackupKeyResponse
 */
export const GetBackupKeyResponse = /*@__PURE__*/ proto3.makeMessageType(
  "sdk.proto.v1.GetBackupKeyResponse",
  () => [
    { no: 1, name: "encrypted_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "updated_at", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "meta", kind: "message", T: Meta },
    { no: 10, name: "error", kind: "message", T: Error },
  ],
);

/**
 * @generated from message sdk.proto.v1.GetCurrentUserProfileRequest
 */
export const GetCurrentUserProfileRequest = /*@__PURE__*/ proto3.makeMessageType(
  "sdk.proto.v1.GetCurrentUserProfileRequest",
  () => [
    { no: 1, name: "http_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "access_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "timeout", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 4, name: "track_params", kind: "message", T: TrackParams },
    { no: 10, name: "optional_params", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message sdk.proto.v1.GetCurrentUserProfileResponse
 */
export const GetCurrentUserProfileResponse = /*@__PURE__*/ proto3.makeMessageType(
  "sdk.proto.v1.GetCurrentUserProfileResponse",
  () => [
    { no: 1, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "updated_at", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "meta", kind: "message", T: Meta },
    { no: 10, name: "error", kind: "message", T: Error },
  ],
);

/**
 * @generated from message sdk.proto.v1.KeyDistributionRequest
 */
export const KeyDistributionRequest = /*@__PURE__*/ proto3.makeMessageType(
  "sdk.proto.v1.KeyDistributionRequest",
  () => [
    { no: 1, name: "websocket_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "access_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "private_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "timeout", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 5, name: "track_params", kind: "message", T: TrackParams },
    { no: 10, name: "optional_params", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message sdk.proto.v1.KeyDistributionResponse
 */
export const KeyDistributionResponse = /*@__PURE__*/ proto3.makeMessageType(
  "sdk.proto.v1.KeyDistributionResponse",
  () => [
    { no: 1, name: "key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "meta", kind: "message", T: Meta },
    { no: 10, name: "error", kind: "message", T: Error },
  ],
);

/**
 * @generated from message sdk.proto.v1.RefreshKeyRequest
 */
export const RefreshKeyRequest = /*@__PURE__*/ proto3.makeMessageType(
  "sdk.proto.v1.RefreshKeyRequest",
  () => [
    { no: 1, name: "websocket_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "access_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "timeout", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 5, name: "track_params", kind: "message", T: TrackParams },
    { no: 10, name: "optional_params", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message sdk.proto.v1.RefreshKeyResponse
 */
export const RefreshKeyResponse = /*@__PURE__*/ proto3.makeMessageType(
  "sdk.proto.v1.RefreshKeyResponse",
  () => [
    { no: 1, name: "key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "meta", kind: "message", T: Meta },
    { no: 10, name: "error", kind: "message", T: Error },
  ],
);

/**
 * @generated from message sdk.proto.v1.Meta
 */
export const Meta = /*@__PURE__*/ proto3.makeMessageType(
  "sdk.proto.v1.Meta",
  () => [
    { no: 1, name: "request_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message sdk.proto.v1.TrackParams
 */
export const TrackParams = /*@__PURE__*/ proto3.makeMessageType(
  "sdk.proto.v1.TrackParams",
  () => [
    { no: 1, name: "enable", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "timeout", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ],
);

